### ISSUE TITLE
add fav icon

### ISSUE THREAD

**Issue by xiaoxiae** [xiaoxiae/meziklasi#15]
Currently, the website doesn't have an icon, which doesn't look too nice.

**Comment by yagarea** [comment]
This issue is related do #11 . If we find someone for logo it is not a problem to ask for icon.

**Comment by filiptronicek** [comment]
We could also just make the favicon from an emoji, like the 🌾 one.

**Comment by yagarea** [comment]
> We could also just make the favicon from an emoji, like the ear_of_rice one.

This could be easy solution without any need of creativity and copyright problems. Kinda like it.

The thing is every system displays this emoji in different way. Which one will we choose ?

**Comment by filiptronicek** [comment]
From [this Emojipedia article](https://emojipedia.org/sheaf-of-rice/), I really like Microsoft's design, it is very minimalistic. The other ones I like are from Google or Apple.

**Comment by yagarea** [comment]
I hate to say it but I also really like the microsoft one. I'll implement it and you tell me what you think

**Comment by yagarea** [comment]
Tohle asi už můžu uzavřít, že ?

**Comment by xiaoxiae** [comment]
![image](https://user-images.githubusercontent.com/25018064/183312126-cf315978-e957-4a87-bfee-5dd590bba059.png)
