### ISSUE TITLE
transfer from Wedos to DigitalOcean

### ISSUE THREAD

**Issue by xiaoxiae** [xiaoxiae/meziklasi#22]
- [ ] ditch the upload script (+ login.py)
- [ ] setup domain
- [ ] create private Git repository for the organization

**Comment by filiptronicek** [comment]
We could also use GitHub pages, couldn't we? If there are any build steps we need to take we could make them into a GitHub action which would build the site and upload it to GitHub Pages.

GitHub Action that could help a lot with this: https://github.com/marketplace/actions/publish-to-github-pages

**Comment by xiaoxiae** [comment]
Fair point.

**Comment by yagarea** [comment]
I am perfectly ok with both solutions. You have my trust to choose the best one. Just write _build_ and _deploy_ instruction into readme file.
