### ISSUE TITLE
Locally served instance still loads resources from server

### ISSUE THREAD

**Issue by yagarea** [xiaoxiae/meziklasi#25]
When you run `bundle exec jekyll serve --trace` jekyll will generate pages loading files from remote server:

```html
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- PAGE TITLE AND DESCRIPTION -->

            <title>Meziklasí</title>

        <meta name="description" content="Tato stránka je dedikována mýtické vesnici Meziklasí, nacházející se ve středu a v pátek na východě České Republiky.         ">

        <!-- FAVICON -->
        <link rel="icon" type="image/ico" href="https://meziklasi.cz/favicon.ico">

        <!-- CSS -->
        <link rel="stylesheet" href="https://meziklasi.cz/assets/css/main.css">

        <!-- KATEX -->
        <link rel="stylesheet" href="https://meziklasi.cz/assets/css/katex.min.css">

...
```

This needs to be fixed for proper testing without server deployment.

**Comment by xiaoxiae** [comment]
Add another config with localhost url?

**Comment by yagarea** [comment]
In my projects I have references in this form:
```html
<link href="{{site.url}}{{site.baseurl}}/assets/css/style.css" type="text/css" rel="stylesheet"/>
```
and it works great. 

I would prefer universal solution instead of multiple config files.

**Comment by xiaoxiae** [comment]
Btw: nechceme přepnout do češtiny?

Jako ano, to tam tak není? Myslel jsem, že `{{ site.url }}` se nepřepíná podle build a serve (teda alespoň u mě né).

**Comment by yagarea** [comment]
Btw: Klidně.

Já mám `jekyll 4.1.1` a opravdu mi to tam hodí `localhost` když ho pustím jako `serve`. Nemám na to žádné special nastavení nebo aspoň o něm nevím.

**Comment by filiptronicek** [comment]
Myslím že jsem ten hlavní problém s tím `main.css` souborem omylem opravil v https://github.com/Meziklassociation/meziklasi/pull/27/commits/d896a1d82c33875c15aa5f1e5a120ec5c6cac3ed, vlastně jsem jenom změnil z absolutních URL adres na relativní - podle mě nás používání relativních odkazů o nic neobírá a mohli bychom to nandat na zbytek odkazů.

**Comment by yagarea** [comment]
Jsem pro. Je to docela čisté a zaručíme tím univerzální funkčnost projektu bez ohledu jak spuštěný.

**Comment by xiaoxiae** [comment]
Grepování lokálního buildu mastera nevrací žádné meziklasi.cz, takže zavírám.
