### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by yagarea** [xiaoxiae/meziklasi#33]
Asi by stálo za to si rozmyslet licencování tohoto projektu.

Já navrhuji, aby 
- kód byl pod licencí `GPLv3`
- obsah pod [`CC BY 4.0`](https://creativecommons.org/licenses/by/4.0/)

**Comment by xiaoxiae** [comment]
Za mě souhlas. Pokud nikdo neprotestuje, tak to klidně přidej.

**Comment by yagarea** [comment]
Done
